### ISSUE TITLE
Design Workflow Definition Model and DSL

### ISSUE THREAD

**Issue by jane-alesi** [jane-alesi/finflow-enterprise-automation#9]
# Design Workflow Definition Model and DSL

## Description
Create a comprehensive workflow definition model and Domain Specific Language (DSL) that allows financial institutions to define complex business processes in a declarative, auditable manner.

## Business Value
- Enables business users to define workflows without deep technical knowledge
- Provides clear, auditable workflow definitions for compliance
- Supports complex financial process modeling
- Enables workflow versioning and change management
- Facilitates regulatory review and approval processes

## Technical Requirements
- JSON/YAML-based workflow definition format
- Support for conditional logic and branching
- Integration with compliance validation rules
- Workflow versioning and migration support
- Visual workflow designer compatibility
- Validation and schema enforcement

## Workflow Definition Structure
```yaml
# Example workflow definition
workflow:
  name: "payment-processing"
  version: "1.0.0"
  description: "Standard payment processing workflow"
  
  compliance:
    regulations: ["MiFID II", "PSD3", "GDPR"]
    auditLevel: "FULL"
    
  steps:
    - id: "validate-payment"
      type: "validation"
      service: "payment-validator"
      rules:
        - "amount > 0"
        - "account.status == ACTIVE"
      onFailure: "reject-payment"
      
    - id: "compliance-check"
      type: "compliance"
      service: "compliance-engine"
      regulations: ["MiFID II", "PSD3"]
      onFailure: "compliance-review"
      
    - id: "process-payment"
      type: "service-call"
      service: "payment-processor"
      timeout: "30s"
      retry:
        maxAttempts: 3
        backoff: "exponential"
```

## DSL Features
- **Declarative Syntax**: Clear, readable workflow definitions
- **Conditional Logic**: Support for if/then/else constructs
- **Error Handling**: Comprehensive error handling and compensation
- **Parallel Execution**: Support for parallel workflow branches
- **Integration Points**: Clear service integration definitions
- **Compliance Integration**: Built-in compliance rule references

## Acceptance Criteria
- [ ] Complete workflow definition schema
- [ ] JSON/YAML validation for workflow definitions
- [ ] Support for all required workflow patterns
- [ ] Integration with workflow engine
- [ ] Versioning and migration support
- [ ] Documentation and examples

## Definition of Done
- Workflow definition schema documented
- Validation rules implemented
- Integration with workflow engine tested
- Example workflows created
- Migration strategy defined

## Parent Issue: #4
